<a href="https://colab.research.google.com/github/ptk18/Data-Science-Analytics/blob/main/65011466_PandasLecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas
pandas.__version__

'2.1.4'

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.Series([0.25,0.5,0.75,1.])

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data[1]

0.5

In [ ]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [ ]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
data['b']

0.5

In [ ]:
data = pd.Series([0.25, 0.5, 0.75,1.0], index = [2,5,3,7])

In [ ]:
population_dict = {'California' : 38332521, 'Texas' : 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois':12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population['California']

38332521

In [ ]:
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [ ]:
pd.Series([2,4,6])


0    2
1    4
2    6
dtype: int64

In [ ]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [ ]:
pd.Series({2:'a' , 1:'b', 3:'c'}, index=[3,2])

3    c
2    a
dtype: object

In [ ]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Floridia' :170312, 'Illinois':149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Floridia      170312
Illinois      149995
dtype: int64

In [ ]:
states = pd.DataFrame({'population' : population, 'area':area})
states

population      area
California  38332521.0  423967.0
Florida     19552860.0       NaN
Floridia           NaN  170312.0
Illinois    12882135.0  149995.0
New York    19651127.0  141297.0
Texas       26448193.0  695662.0

In [ ]:
states.index

Index(['California', 'Florida', 'Floridia', 'Illinois', 'New York', 'Texas'], dtype='object')

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

In [ ]:
states['area']

California    423967.0
Florida            NaN
Floridia      170312.0
Illinois      149995.0
New York      141297.0
Texas         695662.0
Name: area, dtype: float64

In [ ]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [ ]:
data = [{'a':i, 'b': 2*i } for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [ ]:
pd.DataFrame([{'a':1,'b':2},{'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [ ]:
pd.DataFrame({'population':population, 'area':area})

population      area
California  38332521.0  423967.0
Florida     19552860.0       NaN
Floridia           NaN  170312.0
Illinois    12882135.0  149995.0
New York    19651127.0  141297.0
Texas       26448193.0  695662.0

In [ ]:
pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])

foo       bar
a  0.309469  0.251142
b  0.752134  0.035761
c  0.852898  0.545810

In [ ]:
A = np.zeros(3, dtype = [('A','i8'),('B','f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [ ]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

# 16.08.2024

In [ ]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [ ]:
ind = pd.Index([2,3,5,7,11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [ ]:
ind[1]

3

In [ ]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [ ]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [ ]:
#ind[1] = 0 # index obj differ from Numpy indices are immutable(cannot be change) so will be error

In [ ]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])
intersection = indA.intersection(indB)
intersection

Index([3, 5, 7], dtype='int64')

In [ ]:
union = indA.union(indB)
union

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [ ]:
symmetric_diff = indA.symmetric_difference(indB)
symmetric_diff

Index([1, 2, 9, 11], dtype='int64')

In [ ]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
data['b']

0.5

In [ ]:
'a' in data

True

In [ ]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [ ]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [ ]:
#slicing by explicit index (include final index)
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [ ]:
#slicing by inplicit index (not including the final index)
data[0:2]

a    0.25
b    0.50
dtype: float64

In [ ]:
#masking
data[(data>3) & (data<0.8)]

Series([], dtype: float64)

In [ ]:
#fancy indexing
data[['a','e']]

a    0.25
e    1.25
dtype: float64

In [ ]:
data = pd.Series(['a','b','c','d'],index=[1,'x','y',3])
data

1    a
x    b
y    c
3    d
dtype: object

In [ ]:
#implicit index when slicing
data[1:3]

x    b
y    c
dtype: object

In [ ]:
#explicit index when indexing
data[1]

'a'

In [ ]:
data.loc[1] #loc => explicit indexing (not position based index) just treat as label

'a'

In [ ]:
data.loc[1:3] #label based indexing (is not integer position based, it is explicit)

1    a
x    b
y    c
3    d
dtype: object

In [ ]:
data.iloc[1] # iloc => implicit indexing (take is as position based integer) 'b' is at index 1

'b'

In [ ]:
data.iloc[1:3]

x    b
y    c
dtype: object

In [ ]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297, 'Floridia': 170312, 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Floridia': 19552860, 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Floridia    170312  19552860
Illinois    149995  12882135

In [ ]:
data['area'] # suggest to use this over data.area

California    423967
Texas         695662
New York      141297
Floridia      170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.area

California    423967
Texas         695662
New York      141297
Floridia      170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.area is data['area']

True

In [ ]:
data.pop

<bound method DataFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Floridia    170312  19552860
Illinois    149995  12882135>

In [ ]:
data.pop is data['pop'] # column name 'pop' is confused with built in method pop

False

In [ ]:
data['density'] = data['pop'] / data['area'] # adding new column 'density' calculated the second column over the first column
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Floridia    170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data.values # raw data 2D arrary can be accessed with values attributes

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [ ]:
data.T #swaps rows and columns -> allwos array-like observations

California         Texas      New York      Floridia      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [ ]:
data.values[0] # accessing the row of dataframe (index of the row)

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [ ]:
data['area'] # accessing the column we need key (the name of column)

California    423967
Texas         695662
New York      141297
Floridia      170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.iloc[:3, :2] #when we see implicit indexing everything treated as index

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [ ]:
data.loc[:'Illinois', :'pop'] #explicit indexing treated as label up to that label

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Floridia    170312  19552860
Illinois    149995  12882135

In [ ]:
data.loc[data.density > 100, ['pop', 'density']] # the first place is always for row, the second is for column

pop     density
New York  19651127  139.076746
Floridia  19552860  114.806121

In [ ]:
data.iloc[0,2] = 90 # assgining row no '0' column '2' to the value
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Floridia    170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data['Floridia':'Illinois']

area       pop     density
Floridia  170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [ ]:
data[1:3] #treated as implicit indexing if we don't sepcify iloc or loc

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [ ]:
data[data.density > 100] # masking operations interpreted as row-wise, not column-wise

area       pop     density
New York  141297  19651127  139.076746
Floridia  170312  19552860  114.806121

In [ ]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4)) #starts from 0 to 10
ser

0    6
1    3
2    7
3    4
dtype: int64

In [ ]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [ ]:
np.exp(ser) # exponential of the series

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [ ]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [ ]:
area = pd.Series({'Alaska' : 1723337, 'Texas' : 695662, 'California' : 423967}, name = 'area')
population = pd.Series({'California': 38332521, 'Texas' : 26448193, 'New York':19651127},name = 'population')

In [ ]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [ ]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [ ]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [ ]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),columns=list('AB')) # 2 by 2 matrix start from 0 to 19
A

A   B
0  1  11
1  5   1

In [ ]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)), columns= list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [ ]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [ ]:
area = pd.Series({'Alaska': 17233337, 'Texas':695662, 'California':423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York':19651127}, name ='population')

In [ ]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [ ]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [ ]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [ ]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [ ]:
A = pd.DataFrame(rng.randint(0,20, (2,2)), columns = list('AB'))
A

A   B
0  19   2
1   4  18

In [ ]:
B = pd.DataFrame(rng.randint(0,10, (3,3)), columns = list('BAC'))
B

B  A  C
0  6  4  8
1  6  1  3
2  8  1  9

In [ ]:
A + B

A     B   C
0  23.0   8.0 NaN
1   5.0  24.0 NaN
2   NaN   NaN NaN

In [ ]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A      B      C
0  23.00   8.00  18.75
1   5.00  24.00  13.75
2  11.75  18.75  19.75

In [ ]:
A = rng.randint(10,size=(3,4))
A

array([[3, 1, 5, 5],
       [9, 3, 5, 1],
       [9, 1, 9, 3]])

In [ ]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 6,  2,  0, -4],
       [ 6,  0,  4, -2]])

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  6  2  0 -4
2  6  0  4 -2

In [ ]:
df.subtract(df['R'],axis = 0)

Q  R  S  T
0  2  0  4  4
1  6  0  2 -2
2  8  0  8  2

In [ ]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    5
Name: 0, dtype: int64

In [ ]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  6.0 NaN  0.0 NaN
2  6.0 NaN  4.0 NaN

In [ ]:
import numpy as np
import pandas as pd

vals1= np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [ ]:
for dtype in ['object', 'int']:
  print("dtype=",dtype)

  %timeit np.arange(1E6, dtype=dtype).sum()
  print()

dtype= object
85.2 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype= int
1.07 ms ± 228 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [ ]:
#vals1.sum()

In [ ]:
vals2 = np.array([1,np.nan, 3,4])
vals2.dtype

dtype('float64')

In [ ]:
1 + np.nan

nan

In [ ]:
0 * np.nan

nan

In [ ]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [ ]:
np.nansum(vals2),np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [ ]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
x=pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [ ]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [ ]:
data = pd.Series([1,np.nan, 'hello',None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [ ]:
data.dropna()

0        1
2    hello
dtype: object

In [ ]:
df = pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [ ]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [ ]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [ ]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [ ]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [ ]:
#forward-fill
data.ffill()

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [ ]:
#backward-fill
data.bfill()

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [ ]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [ ]:
df.ffill(axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
index = [('California', 2000),('California', 2010),('New York', 2000),('New York', 2010),('Texas', 2000),('Texas', 2010)]
populations = [33871648,37253956,18976457,19378102,20851820,25145561]
pop = pd.Series(populations,index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [ ]:
pop[('California',2010):('Texas',2000)]


(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [ ]:
pop[[i for i in pop.index if i[1]==2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [ ]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [ ]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [ ]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [ ]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
pop_df = pd.DataFrame({'total':pop, 'under18':[9267089, 9284094, 4687374, 4318033, 5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [ ]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [ ]:
df = pd.DataFrame(np.random.rand(4,2), index=[['a','a','b','b'],[1,2,1,2]],columns=['data1','data2'])
df

data1     data2
a 1  0.312485  0.114332
  2  0.172674  0.496069
b 1  0.011776  0.857397
  2  0.925563  0.424053

In [ ]:
data = {('California', 2000): 33871648,('California', 2010):37253956,('New York', 2000) : 20851820,('New York', 2010):25145561,('Texas', 2000) :18976457,('Texas', 2010):19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
New York    2000    20851820
            2010    25145561
Texas       2000    18976457
            2010    19378102
dtype: int64

In [ ]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [ ]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [ ]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [ ]:
pd.MultiIndex(levels=[['a','b'],[1,2]], codes=[[0,0,1,1],[0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [ ]:
pop.index.names=['state','year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],names=['subject','type'])

data = np.round(np.random.randn(4,6),1)
data[:, ::2] *= 10
data += 37

health_data = pd.DataFrame(data,index=index, columns=columns)
health_data


subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      24.0  36.3  43.0  36.2  34.0  37.1
     2      41.0  35.8  42.0  37.0  24.0  38.8
2014 1      45.0  37.7  37.0  36.6  31.0  36.3
     2      21.0  38.0  46.0  38.3  26.0  36.0

In [ ]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      43.0  36.2
     2      42.0  37.0
2014 1      37.0  36.6
     2      46.0  38.3

In [ ]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
pop['California',2000]

33871648

In [ ]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [ ]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [ ]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [ ]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [ ]:
pop[['California','Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      24.0  36.3  43.0  36.2  34.0  37.1
     2      41.0  35.8  42.0  37.0  24.0  38.8
2014 1      45.0  37.7  37.0  36.6  31.0  36.3
     2      21.0  38.0  46.0  38.3  26.0  36.0

In [ ]:
health_data['Guido','HR']

year  visit
2013  1        43.0
      2        42.0
2014  1        37.0
      2        46.0
Name: (Guido, HR), dtype: float64

In [ ]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      24.0  36.3
     2      41.0  35.8

In [ ]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        24.0
      2        41.0
2014  1        45.0
      2        21.0
Name: (Bob, HR), dtype: float64

In [ ]:
#health_data.iloc[(:,1),(:,'HR')]

In [ ]:
idx=pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      24.0  43.0  34.0
2014 1      45.0  37.0  31.0

In [ ]:
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names =['char','int']
data

char  int
a     1      0.214792
      2      0.888176
c     1      0.745108
      2      0.566598
b     1      0.286731
      2      0.108182
dtype: float64

In [ ]:
try:
  data['a':'b']
except KeyError as e:
  print(type(e))
  print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [ ]:
data = data.sort_index()
data

char  int
a     1      0.214792
      2      0.888176
b     1      0.286731
      2      0.108182
c     1      0.745108
      2      0.566598
dtype: float64

In [ ]:
data['a':'b']

char  int
a     1      0.214792
      2      0.888176
b     1      0.286731
      2      0.108182
dtype: float64

In [ ]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [ ]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [ ]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [ ]:
pop_flat.set_index(['state','year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [ ]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      24.0  36.3  43.0  36.2  34.0  37.1
     2      41.0  35.8  42.0  37.0  24.0  38.8
2014 1      45.0  37.7  37.0  36.6  31.0  36.3
     2      21.0  38.0  46.0  38.3  26.0  36.0

In [ ]:
data_mean = health_data.groupby(level='year').mean()
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     32.5  36.05  42.5  36.60  29.0  37.95
2014     33.0  37.85  41.5  37.45  28.5  36.15

In [ ]:
data_mean.T.groupby(level='type').mean()

year       2013       2014
type                      
HR    34.666667  34.333333
Temp  36.866667  37.150000